# Generated by Django 4.2.14 on 2025-05-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='characteristic',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
